# Generated by Django 3.0.6 on 2020-11-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_guard', models.CharField(max_length=20, unique=True, verbose_name='códido do guarda')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'guarda',
                'verbose_name_plural': 'guardas',
            },
        ),
    ]
