# Generated by Django 3.0.6 on 2020-11-10 00:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0002_auto_20201109_2011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='placa veículo')),
                ('occurrence_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='tipo')),
                ('occurence_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('location', models.CharField(blank=True, max_length=400, null=True, verbose_name='localização')),
                ('status', models.IntegerField(choices=[(0, 'Enviado'), (1, 'Recebido')], default=0)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='data')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guards.Guard', verbose_name='guarda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='nome usuário')),
            ],
            options={
                'verbose_name': 'ocorrência',
                'verbose_name_plural': 'ocorrências',
                'ordering': ('-created_at',),
            },
        ),
    ]
