# Generated by Django 3.0.6 on 2020-11-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_auto_20201109_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='occurence_title',
            new_name='occurrence_title',
        ),
    ]
