# Generated by Django 3.0.6 on 2020-11-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0002_auto_20201109_2011'),
        ('occurrences', '0003_auto_20201109_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guards.Guard', verbose_name='guarda'),
        ),
    ]
