# Generated by Django 3.0.6 on 2020-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_auto_20201111_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='observation',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='observação'),
        ),
    ]
