# Generated by Django 3.0.6 on 2020-11-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_occurrence_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='denúncia anônima'),
        ),
    ]
