# Generated by Django 3.0.6 on 2020-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0007_auto_20201113_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='denúncia anônima'),
        ),
    ]
