# Generated by Django 3.0.6 on 2020-11-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0009_auto_20201113_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagem'),
        ),
    ]
