# Generated by Django 3.0.6 on 2020-11-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0010_occurrence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='occurrences', verbose_name='imagem'),
        ),
    ]
